// This file will be auto-generated by: npx supabase gen types typescript
// For now, a minimal placeholder so TypeScript doesn't complain

export interface Database {
  public: {
    Tables: {
      profiles: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      clients: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      inspections: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      defects: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      photos: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      floor_plans: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      pins: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      checklist_templates: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      checklist_items: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      voice_notes: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      reports: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      companies: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
